"""empty message

Revision ID: 6a7668554e03
Revises: 9c0db7d5fbc0
Create Date: 2023-03-23 23:53:18.144797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7668554e03'
down_revision = '9c0db7d5fbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GAMES', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forSale', sa.Integer(), nullable=False))

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('address')

    with op.batch_alter_table('GAMES', schema=None) as batch_op:
        batch_op.drop_column('forSale')

    # ### end Alembic commands ###
