"""empty message

Revision ID: 9c0db7d5fbc0
Revises: 
Create Date: 2023-03-23 21:57:32.549675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0db7d5fbc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GAMES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('ipfsLink', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('WALLETS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('USER_TO_GAME',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('gameId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gameId'], ['GAMES.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('userId', 'gameId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('USER_TO_GAME')
    op.drop_table('WALLETS')
    op.drop_table('USERS')
    op.drop_table('GAMES')
    # ### end Alembic commands ###
